version: '3.4'

services:
  algdatagateway.api:
    image: ${DOCKER_REGISTRY-}algdatagatewayapi
    build:
      context: .
      dockerfile: AlgDataGateway.API/AlgDataGateway.API/Dockerfile
    ports:
    - 5003:443

  datastructure.api:
    image: ${DOCKER_REGISTRY-}datastructureapi
    build:
      context: .
      dockerfile: DataStructure.API/Dockerfile
    ports:
    - 5002:80

  algorithms.api:
    image: ${DOCKER_REGISTRY-}algorithmsapi
    build:
      context: .
      dockerfile: Algorithms.API/Dockerfile
    ports:
    - 5001:80

  mongo:
    image: mongo
    restart: always
    container_name: algdataapidb
    ports:
     - 28018:27017
    volumes:
    - .\AlgDataVolume:\data\db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo